// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vega.Models;

namespace vega.Migrations
{
    [DbContext(typeof(VegaDbContext))]
    partial class VegaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("vega.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CarModels");

                    b.HasData(
                        new { Id = 1, Name = "Prado" },
                        new { Id = 2, Name = "Auris" },
                        new { Id = 3, Name = "Camry" },
                        new { Id = 4, Name = "X6" },
                        new { Id = 5, Name = "CRV" }
                    );
                });

            modelBuilder.Entity("vega.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new { Id = 1, Name = "4 wheel drive" },
                        new { Id = 2, Name = "ABS" },
                        new { Id = 3, Name = "Central locking" },
                        new { Id = 4, Name = "Reverse Camera" }
                    );
                });

            modelBuilder.Entity("vega.Models.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarModelId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.ToTable("Makes");

                    b.HasData(
                        new { Id = 1, CarModelId = 1, Name = "Toyota" },
                        new { Id = 2, CarModelId = 4, Name = "BMW" },
                        new { Id = 3, CarModelId = 5, Name = "Honda" },
                        new { Id = 4, CarModelId = 2, Name = "Toyota" }
                    );
                });

            modelBuilder.Entity("vega.Models.Make", b =>
                {
                    b.HasOne("vega.Models.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
